### ISSUE TITLE
Update ALVR to 20.9.1

### ISSUE THREAD

**Issue by ellwoodb** [PassiveLemon/lemonake#2]
Hey, firstly, I have to say, that I really like your repo. It has helped me a lot in setting up my own NixOS config and getting ALVR to work.

I saw, that your version of the ALVR package is one version behind. I took the liberty of copying your code and modifying it a bit. I needed to add "SDL2" to the buildInputs for it to work, but now I got the newest version 20.9.1 to work on my system.

Here is my code: [https://github.com/ellwoodb/nixos-config/blob/main/pkgs/alvr/default.nix](https://github.com/ellwoodb/nixos-config/blob/main/pkgs/alvr/default.nix)

I have to say, I am not an expert in Nix and have not really written any packages, so if you see any issues please let me know. If my code is good, maybe you could update your repo, or even make a pull request to nixpkgs (I saw you contributing there as well).

Have a nice day!

**Comment by PassiveLemon** [comment]
Thank you! I will update this repo but not Nixpkgs as other contributors are working towards building entirely from source.

**Comment by ellwoodb** [comment]
Sounds good. Glad I could help!
